// S13b — the calibration check for `textMetrics.ts`.
//
// A width model that only ever agrees with itself proves nothing (the same
// failure as a fixture generated by the code it is meant to check). The
// samples below are WHOLE strings measured in real Chrome with the real font
// stack — single words through 64-character sentences, both locales, every
// size the components use — so the per-character model is checked against
// the browser it stands in for, not against its own arithmetic.
//
// Three bounds, all load-bearing:
//   - the raw model may under-report by no more than
//     `MODEL_UNDERESTIMATE_MARGIN` (0.5%). That constant is not a guess for
//     safety's sake: it is the bound this test enforces, so the margin the
//     fit budgets rely on cannot be widened without re-measuring.
//   - the raw model must stay under +2.5%: the residual is pair kerning,
//     which a per-character sum ignores. Beyond that the model is not
//     trustworthy enough to gate anything.
//   - the upper bound must never be narrower than Chrome, on any sample.
//     That is the property every budget in `esLayoutFit.test.tsx` leans on.

import { describe, expect, it } from "vitest";
import { en } from "../i18n/en";
import { es } from "../i18n/es";
import {
  MODEL_UNDERESTIMATE_MARGIN,
  calibratedStyles,
  measureTextWidth,
  measureTextWidthUpperBound,
} from "./textMetrics";

const CHROME_SAMPLES = [
  { text: "Reanudar", style: { size: 14, weight: 500 } as const, chrome: 62.9613 },
  { text: "Cambiar", style: { size: 14, weight: 500 } as const, chrome: 55.3574 },
  { text: "Detener", style: { size: 14, weight: 500 } as const, chrome: 52.811 },
  { text: "Recuperar", style: { size: 14, weight: 500 } as const, chrome: 68.1214 },
  { text: "Descartar", style: { size: 14, weight: 500 } as const, chrome: 64.9769 },
  { text: "Iniciar", style: { size: 14, weight: 500 } as const, chrome: 40.0439 },
  { text: "Pausar", style: { size: 14, weight: 500 } as const, chrome: 45.1855 },
  { text: "Resume", style: { size: 14, weight: 500 } as const, chrome: 52.8639 },
  { text: "Total de hoy", style: { size: 12, weight: 400 } as const, chrome: 68.9531 },
  {
    text: "Se eliminó “Reunión de planificación trimestral”.",
    style: { size: 12, weight: 400 } as const,
    chrome: 269.191,
  },
  { text: "Iniciar / pausar / reanudar", style: { size: 14, weight: 400 } as const, chrome: 163.611 },
  {
    text: "Abrir Tiny Time Tool automáticamente al iniciar sesión",
    style: { size: 14, weight: 400 } as const,
    chrome: 347.004,
  },
  {
    text: "Migración de la base de datos @Distribuidora",
    style: { size: 14, weight: 400 } as const,
    chrome: 292.824,
  },
  {
    text: "Revisión del contrato de mantenimiento @Ayuntamiento #renovación",
    style: { size: 14, weight: 400 } as const,
    chrome: 443.264,
  },
  {
    text: "Los campos de fecha y hora siguen el idioma configurado",
    style: { size: 12, weight: 400 } as const,
    chrome: 325.002,
  },
  { text: "viernes, 21 de agosto de 2026", style: { size: 18, weight: 600 } as const, chrome: 252.791 },
  { text: "22:00", style: { size: 24, weight: 600 } as const, chrome: 70.3945 },
];

describe("textMetrics", () => {
  it("stays inside the calibrated error band against real Chrome", () => {
    for (const sample of CHROME_SAMPLES) {
      const modelled = measureTextWidth(sample.text, sample.style);
      const error = (modelled - sample.chrome) / sample.chrome;
      expect(
        error,
        `"${sample.text}" under-estimated by more than MODEL_UNDERESTIMATE_MARGIN`,
      ).toBeGreaterThan(-MODEL_UNDERESTIMATE_MARGIN);
      expect(error, `"${sample.text}" off by more than 2.5%`).toBeLessThan(0.025);
    }
  });

  it("gives an upper bound that is never narrower than Chrome", () => {
    for (const sample of CHROME_SAMPLES) {
      expect(
        measureTextWidthUpperBound(sample.text, sample.style),
        `"${sample.text}" upper bound came in under the browser`,
      ).toBeGreaterThanOrEqual(sample.chrome);
    }
  });

  it("covers every character in both shipped catalogs at every calibrated style", () => {
    const catalogText = [...Object.values(en), ...Object.values(es)].join("");
    for (const style of calibratedStyles()) {
      const [size, weight] = style.split("/").map(Number);
      expect(
        () =>
          measureTextWidth(catalogText, {
            size: size as 12 | 14 | 18 | 24,
            weight: weight as 400 | 500 | 600,
          }),
        `catalog characters unmeasured at ${style}`,
      ).not.toThrow();
    }
  });

  it("refuses an unmeasured character instead of counting it as zero width", () => {
    expect(() => measureTextWidth("你", { size: 14, weight: 400 })).toThrow(/no measured advance/);
  });
});
